# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mnist_predict.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='mnist_predict.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x13mnist_predict.proto\"*\n\x18MnistDigitPredictRequest\x12\x0e\n\x06\x62uffer\x18\x01 \x02(\x0c\"Q\n\x19MnistDigitPredictResponse\x12\x13\n\x0b\x66ound_digit\x18\x01 \x02(\r\x12\x11\n\texec_time\x18\x02 \x02(\r\x12\x0c\n\x04resp\x18\x03 \x02(\x0c')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_MNISTDIGITPREDICTREQUEST = _descriptor.Descriptor(
  name='MnistDigitPredictRequest',
  full_name='MnistDigitPredictRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='buffer', full_name='MnistDigitPredictRequest.buffer', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=65,
)


_MNISTDIGITPREDICTRESPONSE = _descriptor.Descriptor(
  name='MnistDigitPredictResponse',
  full_name='MnistDigitPredictResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='found_digit', full_name='MnistDigitPredictResponse.found_digit', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='exec_time', full_name='MnistDigitPredictResponse.exec_time', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='resp', full_name='MnistDigitPredictResponse.resp', index=2,
      number=3, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=67,
  serialized_end=148,
)

DESCRIPTOR.message_types_by_name['MnistDigitPredictRequest'] = _MNISTDIGITPREDICTREQUEST
DESCRIPTOR.message_types_by_name['MnistDigitPredictResponse'] = _MNISTDIGITPREDICTRESPONSE

MnistDigitPredictRequest = _reflection.GeneratedProtocolMessageType('MnistDigitPredictRequest', (_message.Message,), dict(
  DESCRIPTOR = _MNISTDIGITPREDICTREQUEST,
  __module__ = 'mnist_predict_pb2'
  # @@protoc_insertion_point(class_scope:MnistDigitPredictRequest)
  ))
_sym_db.RegisterMessage(MnistDigitPredictRequest)

MnistDigitPredictResponse = _reflection.GeneratedProtocolMessageType('MnistDigitPredictResponse', (_message.Message,), dict(
  DESCRIPTOR = _MNISTDIGITPREDICTRESPONSE,
  __module__ = 'mnist_predict_pb2'
  # @@protoc_insertion_point(class_scope:MnistDigitPredictResponse)
  ))
_sym_db.RegisterMessage(MnistDigitPredictResponse)


# @@protoc_insertion_point(module_scope)
