# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mnist_predict.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='mnist_predict.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x13mnist_predict.proto\"!\n\x0epb_msg_version\x12\x0f\n\x07version\x18\x01 \x02(\r\"$\n\x12pb_msg_predict_req\x12\x0e\n\x06\x62uffer\x18\x01 \x02(\x0c\"K\n\x13pb_msg_predict_resp\x12\x13\n\x0b\x66ound_digit\x18\x01 \x02(\r\x12\x11\n\texec_time\x18\x02 \x02(\r\x12\x0c\n\x04resp\x18\x03 \x02(\x0c')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_PB_MSG_VERSION = _descriptor.Descriptor(
  name='pb_msg_version',
  full_name='pb_msg_version',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='pb_msg_version.version', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=56,
)


_PB_MSG_PREDICT_REQ = _descriptor.Descriptor(
  name='pb_msg_predict_req',
  full_name='pb_msg_predict_req',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='buffer', full_name='pb_msg_predict_req.buffer', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=58,
  serialized_end=94,
)


_PB_MSG_PREDICT_RESP = _descriptor.Descriptor(
  name='pb_msg_predict_resp',
  full_name='pb_msg_predict_resp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='found_digit', full_name='pb_msg_predict_resp.found_digit', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='exec_time', full_name='pb_msg_predict_resp.exec_time', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='resp', full_name='pb_msg_predict_resp.resp', index=2,
      number=3, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=96,
  serialized_end=171,
)

DESCRIPTOR.message_types_by_name['pb_msg_version'] = _PB_MSG_VERSION
DESCRIPTOR.message_types_by_name['pb_msg_predict_req'] = _PB_MSG_PREDICT_REQ
DESCRIPTOR.message_types_by_name['pb_msg_predict_resp'] = _PB_MSG_PREDICT_RESP

pb_msg_version = _reflection.GeneratedProtocolMessageType('pb_msg_version', (_message.Message,), dict(
  DESCRIPTOR = _PB_MSG_VERSION,
  __module__ = 'mnist_predict_pb2'
  # @@protoc_insertion_point(class_scope:pb_msg_version)
  ))
_sym_db.RegisterMessage(pb_msg_version)

pb_msg_predict_req = _reflection.GeneratedProtocolMessageType('pb_msg_predict_req', (_message.Message,), dict(
  DESCRIPTOR = _PB_MSG_PREDICT_REQ,
  __module__ = 'mnist_predict_pb2'
  # @@protoc_insertion_point(class_scope:pb_msg_predict_req)
  ))
_sym_db.RegisterMessage(pb_msg_predict_req)

pb_msg_predict_resp = _reflection.GeneratedProtocolMessageType('pb_msg_predict_resp', (_message.Message,), dict(
  DESCRIPTOR = _PB_MSG_PREDICT_RESP,
  __module__ = 'mnist_predict_pb2'
  # @@protoc_insertion_point(class_scope:pb_msg_predict_resp)
  ))
_sym_db.RegisterMessage(pb_msg_predict_resp)


# @@protoc_insertion_point(module_scope)
