/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.0-dev */

#ifndef PB_MNIST_PREDICT_PB_H_INCLUDED
#define PB_MNIST_PREDICT_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef PB_BYTES_ARRAY_T(1024) pb_msg_predict_req_buffer_t;
typedef struct _pb_msg_predict_req {
    pb_msg_predict_req_buffer_t buffer;
/* @@protoc_insertion_point(struct:pb_msg_predict_req) */
} pb_msg_predict_req;


typedef PB_BYTES_ARRAY_T(100) pb_msg_predict_resp_resp_t;
typedef struct _pb_msg_predict_resp {
    uint32_t found_digit;
    uint32_t exec_time;
    pb_msg_predict_resp_resp_t resp;
/* @@protoc_insertion_point(struct:pb_msg_predict_resp) */
} pb_msg_predict_resp;


typedef struct _pb_msg_version {
    uint32_t version;
/* @@protoc_insertion_point(struct:pb_msg_version) */
} pb_msg_version;


/* Initializer values for message structs */
#define pb_msg_version_init_default              {0}
#define pb_msg_predict_req_init_default          {{0, {0}}}
#define pb_msg_predict_resp_init_default         {0, 0, {0, {0}}}
#define pb_msg_version_init_zero                 {0}
#define pb_msg_predict_req_init_zero             {{0, {0}}}
#define pb_msg_predict_resp_init_zero            {0, 0, {0, {0}}}

/* Field tags (for use in manual encoding/decoding) */
#define pb_msg_predict_req_buffer_tag            1
#define pb_msg_predict_resp_found_digit_tag      1
#define pb_msg_predict_resp_exec_time_tag        2
#define pb_msg_predict_resp_resp_tag             3
#define pb_msg_version_version_tag               1

/* Struct field encoding specification for nanopb */
#define pb_msg_version_FIELDLIST(X, a) \
X(a, STATIC, REQUIRED, UINT32, version, 1)
#define pb_msg_version_CALLBACK NULL
#define pb_msg_version_DEFAULT NULL

#define pb_msg_predict_req_FIELDLIST(X, a) \
X(a, STATIC, REQUIRED, BYTES, buffer, 1)
#define pb_msg_predict_req_CALLBACK NULL
#define pb_msg_predict_req_DEFAULT NULL

#define pb_msg_predict_resp_FIELDLIST(X, a) \
X(a, STATIC, REQUIRED, UINT32, found_digit, 1) \
X(a, STATIC, REQUIRED, UINT32, exec_time, 2) \
X(a, STATIC, REQUIRED, BYTES, resp, 3)
#define pb_msg_predict_resp_CALLBACK NULL
#define pb_msg_predict_resp_DEFAULT NULL

extern const pb_msgdesc_t pb_msg_version_msg;
extern const pb_msgdesc_t pb_msg_predict_req_msg;
extern const pb_msgdesc_t pb_msg_predict_resp_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define pb_msg_version_fields &pb_msg_version_msg
#define pb_msg_predict_req_fields &pb_msg_predict_req_msg
#define pb_msg_predict_resp_fields &pb_msg_predict_resp_msg

/* Maximum encoded size of messages (where known) */
#define pb_msg_version_size                      6
#define pb_msg_predict_req_size                  1027
#define pb_msg_predict_resp_size                 114

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
