/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.0-dev */

#include "mnist_predict.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(pb_msg_version, pb_msg_version, AUTO)


PB_BIND(pb_msg_predict_req, pb_msg_predict_req, 2)


PB_BIND(pb_msg_predict_resp, pb_msg_predict_resp, AUTO)



/* @@protoc_insertion_point(eof) */
